"""Regenerate Plans/Drones/Drone Decisions.md (tables with a sprite per tier row).
Run from the project root: python tools/drone_notes.py
Stats come from data/items_raw.json (Legacy + Reloaded packs) plus the rules written in each section's text."""
import json

BS = chr(92)
NL = "\n"
raw = json.load(open("data/items_raw.json", encoding="utf-8"))
raw = raw if isinstance(raw, list) else raw["items"]
by = {i["id"]: i for i in raw}
tiers = lambda id: by[id]["stats"]["reloaded"]["tiers"]

DMG = ("phyDmg", "expDmg", "eleDmg")
DRAIN = ("heaDmg", "eneDmg", "phyResDmg", "expResDmg", "eleResDmg", "heaCapDmg", "eneCapDmg", "heaColDmg", "eneRegDmg")
COST = ("eneCost", "heaCost")


def rb(id, tier):
    v = tiers(id)[tier]
    return dict(v["base"]), dict(v.get("max") or v["base"])


def scale(b, m, dmg=1.0, drain=1.0, cost=1.0, back=1.0):
    b, m = dict(b), dict(m)
    for x in (b, m):
        for k in DMG:
            if k in x:
                x[k] = [max(1, round(x[k][0] * dmg)), max(1, round(x[k][1] * dmg))]
        for k in DRAIN:
            if k in x:
                x[k] = max(1, round(x[k] * drain))
        for k in COST:
            if k in x:
                x[k] = max(1, round(x[k] * cost))
        if "backfire" in x:
            x["backfire"] = round(x["backfire"] * back)
    return b, m


def ult_row(b, back=1.31):
    """Ultimate: level 1 = the given block, level 100 = damage x1.62, drains x1.45, backfire at half the damage rate (x1.31)."""
    m = dict(b)
    for k in DMG:
        if k in b:
            m[k] = [round(b[k][0] * 1.62), round(b[k][1] * 1.62)]
    for k in DRAIN:
        if k in b:
            m[k] = round(b[k] * 1.45)
    if "backfire" in b:
        m["backfire"] = round(b["backfire"] * back)
    return dict(b), m


def cell(b, m, k):
    a, z = b.get(k), m.get(k, b.get(k))
    if a is None:
        return None
    return f"{a}→{z}" if a != z else f"{a}"


def dmg(b, m):
    for k, l in (("phyDmg", "phy"), ("expDmg", "exp"), ("eleDmg", "ele")):
        if k in b:
            lo = f"{b[k][0]}-{b[k][1]}"
            hi = f"{m[k][0]}-{m[k][1]}"
            return (f"{lo}→{hi}" if lo != hi else lo) + f" {l}"
    return "–"


def drains(b, m):
    o = []
    for k, l in (("heaDmg", "heat"), ("eneDmg", "energy"), ("phyResDmg", "phy res"), ("expResDmg", "exp res"), ("eleResDmg", "ele res"),
                 ("heaCapDmg", "heat cap"), ("eneCapDmg", "en cap"), ("heaColDmg", "cooling"), ("eneRegDmg", "regen")):
        c = cell(b, m, k)
        if c is not None:
            o.append(f"{l} {c}")
    return ", ".join(o) or "–"


def costs(b):
    o = [f"{b[k]} {l}" for k, l in (("eneCost", "energy"), ("heaCost", "heat")) if k in b]
    return " + ".join(o) or "–"


def img(sprite, w=64):
    return f"![[Drones/sprites/{sprite}.png{BS}|{w}]]"


def table(rows):
    o = ["| Tier | Look | Damage | Drain | Backfire | Cost | Range | Weight |", "|---|---|---|---|---|---|---|---|"]
    for lab, sp, b, m in rows:
        rg = f"{b['range'][0]}-{b['range'][1]}" if "range" in b else "–"
        if "uses" in b:
            rg += f", uses {b['uses']}"
        for k in ("push", "pull"):
            if k in b:
                rg += f", {k} {b[k]}"
        bf = cell(b, m, "backfire") or "–"
        o.append(f"| {lab} | {img(sp)} | {dmg(b, m)} | {drains(b, m)} | {bf} | {costs(b)} | {rg} | {b.get('weight', '–')} |")
    return NL.join(o)


def block(title, rows, note=""):
    return f"#### {title}" + NL + (note + NL + NL if note else NL) + table(rows) + NL


out = []
out.append("""# Drone Decisions

All drones are planned (the old full sheet is in `_archive/`). Generated by `tools/drone_notes.py` (edit the script, not this file). Each table is base → max level inside the tier. *Derived / invented* numbers are called out per family. The stat base for everything the data has no numbers for is the Reloaded **Void / Clash / Snack** ladder (`superDroneBasic1–3`, physical / heat / energy).
""")

E3 = (("phy", "superDroneBasic1E"), ("heat", "superDroneBasic2E"), ("ene", "superDroneBasic3E"))

# ---- Basic drones: Common -> Rare
out.append("## Basic drones (`droneBasic1–3`)" + NL +
           "**Common → Rare, 3 types.** A = Common, B = Rare. Orange is physical, red is heat, blue is energy. Unnamed and unreleased in the data, so the names are placeholders and the stats are *invented* from Void / Clash / Snack: Rare = their Epic / 1.69, Common = Rare / 1.9 (the Reloaded ladder), weight x0.75, costs scaled x0.65 (Rare) and x0.35 (Common)." + NL)
for nm, num, src in (("Scout (physical)", "1", "superDroneBasic1E"), ("Flare (heat)", "2", "superDroneBasic2E"), ("Zapper (energy)", "3", "superDroneBasic3E")):
    eb, em = rb(src, "epic")
    rb_, rm_ = scale(eb, em, dmg=1 / 1.69, drain=1 / 1.69, cost=.65)
    cb_, cm_ = scale(rb_, rm_, dmg=1 / 1.9, drain=1 / 1.9, cost=.35 / .65)
    for x in (rb_, rm_, cb_, cm_):
        x["weight"] = round(eb["weight"] * .75)
    out.append(block(nm, [("Common", f"droneBasic{num}A", cb_, cm_), ("Rare", f"droneBasic{num}B", rb_, rm_)]))

# ---- Pointers: Epic -> Legendary
out.append("## Pointers (`drone26`, `drone27`)" + NL +
           "**Epic → Legendary, 3 types each**, one look per type used for both tiers. Legacy names and weights (the Legacy pointers have no Reloaded data, damage about 30-40). Stat base *(derived)*: the Void / Clash / Snack Epic and Legendary blocks; the single pointers x0.8 on damage and drains, the triple pointers x1.0." + NL)
for grp, mult, sprites in (("Pointers", .8, (("Kinetic pointer (physical)", "drone26A", 0), ("Laser pointer (heat)", "drone26C", 1), ("Electric pointer (energy)", "drone26B", 2))),
                          ("Triple pointers", 1.0, (("Triple kinetic pointer (physical)", "drone27A", 0), ("Triple laser pointer (heat)", "drone27C", 1), ("Triple electric pointer (energy)", "drone27B", 2)))):
    for nm, sprite, idx in sprites:
        src = E3[idx][1]
        rows = []
        for tl, tk in (("Epic", "epic"), ("Legendary", "legendary")):
            b, m = rb(src, tk)
            b, m = scale(b, m, dmg=mult, drain=mult)
            b["weight"] = m["weight"] = by[sprite]["stats"]["legacy"][0]["stats"]["weight"]
            rows.append((tl, sprite, b, m))
        out.append(block(nm, rows))

# ---- HurlBat / Nemo / Torment: Rare -> Legendary
out.append("## HurlBat, Nemo, Torment (`droneCapacityDamage1–3`)" + NL +
           "**Rare → Legendary, 3 types.** Looks C, D, E = Rare, Epic, Legendary. Epic and Legendary are the Reloaded stats as they are (they drain the enemy's energy / heat *capacity*); **Rare is derived** as Epic / 1.7 on damage and drains (minimum 1), costs x0.6." + NL)
for nm, num in (("HurlBat (physical)", "1"), ("Nemo (heat)", "2"), ("Torment (energy)", "3")):
    src = f"droneCapacityDamage{num}E"
    eb, em = rb(src, "epic")
    r_b, r_m = scale(eb, em, dmg=1 / 1.7, drain=1 / 1.7, cost=.6)
    rows = [("Rare", f"droneCapacityDamage{num}C", r_b, r_m), ("Epic", f"droneCapacityDamage{num}D", eb, em)]
    lb, lm = rb(src, "legendary")
    rows.append(("Legendary", f"droneCapacityDamage{num}E", lb, lm))
    out.append(block(nm, rows))

# ---- Protectors: Epic -> Mythical
out.append("## Protectors (`droneDamageSelf1–3`)" + NL +
           "**Epic → Mythical, 3 types** (Reloaded Divine dropped, no Ultimate). C = Epic, D = Legendary, E = Mythical. Reloaded stats as they are. They hit hard and **backfire** on their owner." + NL)
for nm, num in (("Selfish Protector (physical)", "1"), ("Backstabbing Protector (heat)", "2"), ("Unreliable Protector (energy)", "3")):
    src = f"droneDamageSelf{num}E"
    rows = []
    for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        rows.append((tl, f"droneDamageSelf{num}{sp_}", b, m))
    out.append(block(nm, rows))

# ---- Guardians: Epic -> Ultimate
out.append("## Guardians (`droneDamageSelfB1–3`)" + NL +
           "**Epic → Ultimate, 3 types.** C = Epic, D = Legendary, E = Mythical + Ultimate. The Reloaded data starts at Legendary, so **Epic is derived** as Legendary x0.62 on damage, drains and backfire (the median Epic / Legendary ratio) and costs x0.6. Ultimate level 1 = Reloaded Divine with the backfire kept at Mythical x1.19; level 100 = damage x1.62, drains x1.45, backfire x1.31 (backfire grows at half the damage rate after Mythical) *(derived)*." + NL)
for nm, num in (("Selfish Guardian (physical)", "1"), ("Backstabbing Guardian (heat)", "2"), ("Unreliable Guardian (energy)", "3")):
    src = f"droneDamageSelfB{num}E"
    lb, lm = rb(src, "legendary")
    eb, em = scale(lb, lm, dmg=.62, drain=.62, cost=.6, back=.62)
    mb, mm = rb(src, "mythical")
    db = dict(tiers(src)["divine"]["base"])
    db["backfire"] = round(mb["backfire"] * 1.19)
    ub, um = ult_row(db)
    rows = [("Epic", f"droneDamageSelfB{num}C", eb, em), ("Legendary", f"droneDamageSelfB{num}D", lb, lm),
            ("Mythical (1→50)", f"droneDamageSelfB{num}E", mb, mm), ("Ultimate (1→100)", f"droneDamageSelfB{num}E", ub, um)]
    out.append(block(nm, rows))

# ---- HeatPoint / Face Shocker: Epic -> Mythical
out.append("## HeatPoint and Face Shocker (`droneHighDamage2–3`)" + NL +
           "**Epic → Mythical, heat and energy only** (no physical version was asked for; no Ultimate). C = Epic, D = Legendary, E = Mythical. Reloaded stats; 3 uses. **HeatPoint's Epic base is corrupt in the data** (161-211 damage, heat 48 and cost 50 are its Mythical numbers next to an Epic max of 71-89), so its Epic base is *derived*: damage x0.72 of the max (Face Shocker's Epic base / max ratio), heat drain 16, cost 18 heat." + NL)
for nm, num in (("HeatPoint (heat)", "2"), ("Face Shocker (energy)", "3")):
    src = f"droneHighDamage{num}E"
    rows = []
    for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        if num == "2" and tk == "epic":
            b["expDmg"] = [round(m["expDmg"][0] * .72), round(m["expDmg"][1] * .72)]
            b["heaDmg"] = 16
            b["heaCost"] = m["heaCost"] = 18
        rows.append((tl, f"droneHighDamage{num}{sp_}", b, m))
    out.append(block(nm, rows))

# ---- droneTypeDamage: Rare -> Epic
out.append("## Sentry, Brand, Volt (`droneTypeDamage1–3`)" + NL +
           "**Rare → Epic, 3 types.** B = Rare, C = Epic. Unnamed and unreleased in the data: placeholder names, *invented* stats from Void / Clash / Snack: Epic = their Epic x1.25 on damage and drains, Rare = Epic / 1.69, costs x0.65 for Rare." + NL)
for nm, num, src in (("Sentry (physical)", "1", "superDroneBasic1E"), ("Brand (heat)", "2", "superDroneBasic2E"), ("Volt (energy)", "3", "superDroneBasic3E")):
    eb, em = rb(src, "epic")
    eb, em = scale(eb, em, dmg=1.25, drain=1.25)
    r_b, r_m = scale(eb, em, dmg=1 / 1.69, drain=1 / 1.69, cost=.65)
    out.append(block(nm, [("Rare", f"droneTypeDamage{num}B", r_b, r_m), ("Epic", f"droneTypeDamage{num}C", eb, em)]))

# ---- Greedy / Swoop / WindForge: Legendary -> Mythical
out.append("## Greedy, Swoop, WindForge (`superDroneTypeDamage1–3`)" + NL +
           "**Legendary → Mythical, 3 types.** D = Legendary, E = Mythical (Reloaded Divine dropped, no Ultimate). Reloaded stats as they are." + NL)
for nm, num in (("Greedy (physical)", "1"), ("Swoop (heat)", "2"), ("WindForge (energy)", "3")):
    src = f"superDroneTypeDamage{num}E"
    rows = []
    for tl, tk, sp_ in (("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        rows.append((tl, f"superDroneTypeDamage{num}{sp_}", b, m))
    out.append(block(nm, rows))

# ---- Void / Clash / Snack: Epic -> Ultimate
out.append("## Void, Clash, Snack (`superDroneBasic1–3`)" + NL +
           "**Epic → Ultimate, 3 types.** C = Epic, D = Legendary, E = Mythical + Ultimate. Reloaded stats; Ultimate level 1 = Reloaded Divine, level 100 = damage x1.62 and drains x1.45 *(derived)*. These three are also the stat base for the drones the data has no numbers for." + NL)
for nm, num in (("Void (physical)", "1"), ("Clash (heat)", "2"), ("Snack (energy)", "3")):
    src = f"superDroneBasic{num}E"
    rows = []
    for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        rows.append((tl, f"superDroneBasic{num}{sp_}", b, m))
    ub, um = ult_row(tiers(src)["divine"]["base"])
    rows.append(("Ultimate (1→100)", f"superDroneBasic{num}E", ub, um))
    out.append(block(nm, rows))

# ---- DustMaker / Murmur / Anguish: Legendary -> Ultimate
out.append("## DustMaker, Murmur, Anguish (`droneRegenDamage1–3`)" + NL +
           "**Legendary → Ultimate, 3 types.** D = Legendary, E = Mythical + Ultimate. Reloaded stats (they also drain the enemy's cooling / regen); Ultimate level 1 = Reloaded Divine, level 100 = damage x1.62 and drains x1.45 *(derived)*." + NL)
for nm, num in (("DustMaker (physical)", "1"), ("Murmur (heat)", "2"), ("Anguish (energy)", "3")):
    src = f"droneRegenDamage{num}E"
    rows = []
    for tl, tk, sp_ in (("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        rows.append((tl, f"droneRegenDamage{num}{sp_}", b, m))
    ub, um = ult_row(tiers(src)["divine"]["base"])
    rows.append(("Ultimate (1→100)", f"droneRegenDamage{num}E", ub, um))
    out.append(block(nm, rows))

# ---- Backstabber / FlameWave / Electrowave: Legendary -> Ultimate
out.append("## Backstabber, FlameWave, Electrowave (`dronePull1`, `dronePush2–3`)" + NL +
           "**Legendary → Ultimate** (the Reloaded range; no band was given). D = Legendary, E = Mythical + Ultimate. Backstabber **pulls** the enemy 1 cell (physical), FlameWave (heat) and **Electrowave** (energy, renamed from Shockwave to avoid the side-weapon name clash) **push** 1. Reloaded stats; Ultimate level 1 = Reloaded Divine, level 100 = damage x1.62 and drains x1.45 *(derived)*. Only these three types exist." + NL)
for nm, src, pre in (("Backstabber (physical)", "dronePull1E", "dronePull1"), ("FlameWave (heat)", "dronePush2E", "dronePush2"), ("Electrowave (energy)", "dronePush3E", "dronePush3")):
    rows = []
    for tl, tk, sp_ in (("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        rows.append((tl, f"{pre}{sp_}", b, m))
    ub, um = ult_row(tiers(src)["divine"]["base"])
    rows.append(("Ultimate (1→100)", f"{pre}E", ub, um))
    out.append(block(nm, rows))

# ---- Tonto / FireFly / Electrolyte: Epic -> Mythical
out.append("## Tonto, FireFly, Electrolyte (`droneRanged1–3`)" + NL +
           "**Epic → Mythical, 3 types** (user: mythic only, no Ultimate; Reloaded Divine dropped). C = Epic, D = Legendary, E = Mythical. Reloaded stats as they are; range 2-4." + NL)
for nm, num in (("Tonto (physical)", "1"), ("FireFly (heat)", "2"), ("Electrolyte (energy)", "3")):
    src = f"droneRanged{num}E"
    rows = []
    for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb(src, tk)
        rows.append((tl, f"droneRanged{num}{sp_}", b, m))
    out.append(block(nm, rows))

# ---- Solar Torch / Flame Spear / Lightning Strike: Epic -> Ultimate
out.append("## Solar Torch, Flame Spear, Lightning Strike (`droneRangedB1–3`)" + NL +
           "**Epic → Ultimate, 3 types** (user: goes to Ultimate). C = Epic, D = Legendary, E = Mythical + Ultimate. The Reloaded data starts at Legendary, so **Epic is derived** as Legendary x0.62 on damage and drains (costs x0.6), as for the Guardians. Reloaded stats otherwise; Ultimate level 1 = Reloaded Divine, level 100 = damage x1.62 and drains x1.45 *(derived)*. Range 3-6. **Rail Gun is renamed Lightning Strike** (it clashed with the side-weapon Rail Gun)." + NL)
for nm, num in (("Solar Torch (physical)", "1"), ("Flame Spear (heat)", "2"), ("Lightning Strike (energy)", "3")):
    src = f"droneRangedB{num}E"
    lb, lm = rb(src, "legendary")
    eb, em = scale(lb, lm, dmg=.62, drain=.62, cost=.6)
    mb, mm = rb(src, "mythical")
    ub, um = ult_row(tiers(src)["divine"]["base"])
    rows = [("Epic", f"droneRangedB{num}C", eb, em), ("Legendary", f"droneRangedB{num}D", lb, lm),
            ("Mythical (1→50)", f"droneRangedB{num}E", mb, mm), ("Ultimate (1→100)", f"droneRangedB{num}E", ub, um)]
    out.append(block(nm, rows))

open("Plans/Drones/Drone Decisions.md", "w", encoding="utf-8").write(NL.join(out))
print("written", len(out))
