"""Regenerate Plans/Legs/Leg Decisions.md (tables with a sprite per tier row).
Run from the project root: python tools/leg_notes.py
Stats come from data/items_raw.json (Legacy + Reloaded packs) plus the rules written in each section's text."""
import json

BS = chr(92)
raw = json.load(open("data/items_raw.json", encoding="utf-8"))
raw = raw if isinstance(raw, list) else raw["items"]
by = {i["id"]: i for i in raw}
tiers = lambda id: by[id]["stats"]["reloaded"]["tiers"]


def rb(id, tier):
    v = tiers(id)[tier]
    return dict(v["base"]), dict(v.get("max") or v["base"])


DMG = ("phyDmg", "expDmg", "eleDmg")
DRAIN = ("heaDmg", "eneDmg", "phyResDmg", "expResDmg", "eleResDmg")


def scale(b, m, mult):
    """Boost HP, stomp damage and drains; walk / jump / push / range / weight / resistances stay."""
    b, m = dict(b), dict(m)
    for x in (b, m):
        if "health" in x:
            x["health"] = round(x["health"] * mult)
        for k in DMG:
            if k in x:
                x[k] = [round(x[k][0] * mult), round(x[k][1] * mult)]
        for k in DRAIN:
            if k in x:
                x[k] = round(x[k] * mult)
    return b, m


def to_heat(b, m):  # energy stomp -> heat stomp: eleDmg -> expDmg, energy drain x0.75 -> heat drain
    b, m = dict(b), dict(m)
    for x in (b, m):
        x["expDmg"] = x.pop("eleDmg")
        x["heaDmg"] = round(x.pop("eneDmg") * .75)
    return b, m


def to_phys(b, m):  # energy stomp -> physical: eleDmg x1.25 -> phyDmg, no drain
    b, m = dict(b), dict(m)
    for x in (b, m):
        a = x.pop("eleDmg")
        x["phyDmg"] = [round(a[0] * 1.25), round(a[1] * 1.25)]
        x.pop("eneDmg")
    return b, m


def rng(v):
    return f"{v[0]}→{v[1]}" if v[0] != v[1] else f"{v[0]}"


def cell(b, m, k):
    a, z = b.get(k), m.get(k, b.get(k))
    if a is None:
        return "–"
    return f"{a}→{z}" if a != z else f"{a}"


def stomp(b, m):
    for k, l in (("phyDmg", "phy"), ("expDmg", "exp"), ("eleDmg", "ele")):
        if k in b:
            lo = f"{b[k][0]}-{b[k][1]}"
            hi = f"{m[k][0]}-{m[k][1]}"
            return (f"{lo}→{hi}" if lo != hi else lo) + f" {l}"
    return "–"


def drain(b, m):
    o = []
    for k, l in (("heaDmg", "heat"), ("eneDmg", "energy"), ("phyResDmg", "phy res"), ("expResDmg", "exp res"), ("eleResDmg", "ele res")):
        if k in b:
            o.append(f"{l} {cell(b, m, k)}")
    return ", ".join(o) or "–"


def img(sprite, w=72):
    return f"![[Legs/sprites/{sprite}.png{BS}|{w}]]"


def table(rows):
    o = ["| Tier | Look | HP | Stomp | Drain | Res | Walk / jump | Push | Range | Weight |", "|---|---|---|---|---|---|---|---|---|---|"]
    for lab, sp, b, m in rows:
        res = "/".join(str(b.get(k, 0)) for k in ("phyRes", "expRes", "eleRes"))
        res = "–" if res == "0/0/0" else res
        o.append(f"| {lab} | {img(sp)} | {cell(b,m,'health')} | {stomp(b,m)} | {drain(b,m)} | {res} | {b.get('walk','–')} / {b.get('jump','–')} | {b.get('push','–')} | {b['range'][0] if 'range' in b else '–'} | {b['weight']} |")
    return "\n".join(o)


def block(title, rows, note=""):
    return f"#### {title}\n" + (note + "\n\n" if note else "\n") + table(rows) + "\n"


out = []
NL = "\n"
out.append("""# Leg Decisions

Legs are planned (the old full sheet is in `_archive/`). Generated by `tools/leg_notes.py` (edit the script, not this file). Each table is base → max level inside the tier. *Derived / invented* numbers are called out per family.
""")

# ---- enemy-only
out.append("## Jeep, Tank, ARMOR TANK legs: enemy-only (`leg1001–1003`)" + NL + "**Enemy use only, no drops** (decided 2026-09-29), like the torsos of the same names (`_enemy_only` in `data/slot_overrides.json`). Legacy stats as they are, no tiers, no levels. *ARMOR TANK's leg was not in the screenshot; it is here with its torso, tell me if it should not be.*" + NL)
rows = ["| Sprite | Name | Weight | HP | Push | Stomp | Drain |", "|---|---|---|---|---|---|---|"]
for i in ("leg1001", "leg1002", "leg1002_2", "leg1002_3", "leg1002_legacy", "leg1003", "leg1003_2", "leg1003_3", "leg1003_legacy"):
    x = by[i]["stats"]["legacy"][0]
    s = x["stats"]
    d_ = ", ".join(f"{s[k][0]} {l}" for k, l in (("phyDmg", "phy"), ("expDmg", "exp"), ("eleDmg", "ele")) if k in s)
    dr = ", ".join(f"{l} {s[k]}" for k, l in (("heaDmg", "heat"), ("eneDmg", "energy")) if k in s) or "–"
    rows.append(f"| {img(i, 56)} | {x['name']} | {s['weight']} | {s.get('health', '–')} | {s.get('push', '–')} | {d_} | {dr} |")
out.append(NL.join(rows) + NL)

# ---- Sparked Runners and Tractors
out.append("## Sparked Runners and the Tractors (`wheels66`, `wheels8`)" + NL +
           "**Legendary → Mythical, 3 types each**, Sparked Runners as the stat base. **Sparked Runners:** D = Legendary, E = Mythical; the native blue is energy, red (heat) and yellow (physical) are new recolours. **Tractors:** the Legacy Steel / Burning / Lightning Tractors have no Reloaded data (HP 35), so they take the Sparked Runners ladder; they have one look each, used for both tiers. Reloaded stats for Sparked Runners as they are (Divine dropped, no Ultimate). Conversion *(derived)*: heat = same damage as explosive with the heat drain at x0.75 of the energy drain, physical = damage x1.25 with no drain. Names of the recolours are placeholders. *Not boosted; say if these should get the x1.35 too.*" + NL)


def sparked(mode):
    r = []
    for tl, tk in (("Legendary", "legendary"), ("Mythical (1→50)", "mythical")):
        b, m = rb("wheels66E", tk)
        if mode == "h":
            b, m = to_heat(b, m)
        if mode == "p":
            b, m = to_phys(b, m)
        r.append((tl, b, m))
    return r


for nm, suf, mode in (("Sparked Runners (energy)", "", None), ("Molten Runners (heat)", "_heat", "h"), ("Granite Runners (physical)", "_phys", "p")):
    sp = (f"wheels66D{suf}", f"wheels66E{suf}")
    out.append(block(nm, [(tl, sp[j], b, m) for j, (tl, b, m) in enumerate(sparked(mode))]))
for nm, sprite, mode in (("Steel Tractors (physical)", "wheels8A", "p"), ("Burning Tractors (heat)", "wheels8B", "h"), ("Lightning Tractors (energy)", "wheels8C", None)):
    out.append(block(nm, [(tl, sprite, b, m) for tl, b, m in sparked(mode)]))

# ---- Massive Feet
out.append("## Massive Stone / Lava / Shocker Feet (`leg80–82`)" + NL +
           "**Rare → Legendary, 3 types** (user changed it from Epic → Mythical). Looks C, D, E = Rare, Epic, Legendary. The Reloaded data starts at Epic, so **Rare is derived** as Epic / 1.7 (HP, stomp damage, drains). **All boosted x1.35** (user): HP, stomp damage and drains. Weight, walk, jump, push, range and resistances stay." + NL)
for nm, num in (("Massive Stone Feet (physical)", "80"), ("Massive Lava Feet (heat)", "81"), ("Massive Shocker Feet (energy)", "82")):
    rows = []
    eb, em = rb(f"leg{num}E", "epic")
    rare_b, rare_m = scale(eb, em, 1 / 1.7)
    rows.append(("Rare", f"leg{num}C", *scale(rare_b, rare_m, 1.35)))
    for tl, tk, sp_ in (("Epic", "epic", "D"), ("Legendary", "legendary", "E")):
        b, m = rb(f"leg{num}E", tk)
        b, m = scale(b, m, 1.35)
        rows.append((tl, f"leg{num}{sp_}", b, m))
    out.append(block(nm, rows))

# ---- Boots and Mass/Barrier legs
out.append("## Rino / Flame / Thunder Boots and Electric Mass / Magma Barrier / Steel Barricade (`leg30`, `leg32`)" + NL +
           "**Mythical → Ultimate only, 3 types each** (user). One look per type, used for both tiers. Both families take the **Reloaded Magma Barrier / Devouring Paws ladder** (`leg32B`, explosive) as their stat base: the Legacy ones have HP 36-50 and no Reloaded data of their own. Mythical = Reloaded Mythical (base to max level 50), Ultimate level 1 = Reloaded Divine, level 100 = HP and stomp damage x1.62 and drains x1.45 *(derived)*. Conversion from the heat base *(derived)*: energy = same damage as electric with the energy drain = heat drain / 0.75; physical = damage x1.25 with no drain. Names are the Legacy ones. *Numbers are identical between the two families; say if the Boots should be the lighter or weaker set.*" + NL)


def ult_row(b):
    m = dict(b)
    m["health"] = round(b["health"] * 1.62)
    for k in DMG:
        if k in b:
            m[k] = [round(b[k][0] * 1.62), round(b[k][1] * 1.62)]
    for k in DRAIN:
        if k in b:
            m[k] = round(b[k] * 1.45)
    return dict(b), m


def from_heat(b, m, mode):
    b, m = dict(b), dict(m)
    for x in (b, m):
        a = x.pop("expDmg")
        d = x.pop("heaDmg")
        if mode == "e":
            x["eleDmg"] = a
            x["eneDmg"] = round(d / .75)
        else:
            x["phyDmg"] = [round(a[0] * 1.25), round(a[1] * 1.25)]
    return b, m


def bm(mode):
    r = []
    b, m = rb("leg32B", "mythical")
    r.append(("Mythical (1→50)", b, m))
    b, m = ult_row(tiers("leg32B")["divine"]["base"])
    r.append(("Ultimate (1→100)", b, m))
    return [(tl, *(from_heat(b, m, mode) if mode else (b, m))) for tl, b, m in r]


for nm, sprite, mode in (("Rino Boots (physical)", "leg30A", "p"), ("Flame Boots (heat)", "leg30B", None), ("Thunder Boots (energy)", "leg30C", "e"),
                         ("Steel Barricade (physical)", "leg32C", "p"), ("Magma Barrier (heat)", "leg32B", None), ("Electric Mass (energy)", "leg32", "e")):
    out.append(block(nm, [(tl, sprite, b, m) for tl, b, m in bm(mode)]))

# ---- Scorching Feet / Iron Boots / Charged Walkers
out.append("## Scorching Feet, Iron Boots, Charged Walkers (`leg60`, `leg61`, `leg62`)" + NL +
           "**Common → Mythical, 3 types** (heat, physical, energy), five looks A-E = Common, Rare, Epic, Legendary, Mythical. The usual Reloaded growth (Divine dropped, no Ultimate), **boosted x1.5** (user): HP, stomp damage and drains. Weight, walk, jump, push and range stay. *`leg62` (Charged Walkers) was not in the screenshot; I put it with its two siblings, tell me if not.*" + NL)
for nm, num in (("Scorching Feet (heat)", "60"), ("Iron Boots (physical)", "61"), ("Charged Walkers (energy)", "62")):
    rows = []
    for j, (tl, tk) in enumerate((("Common", "common"), ("Rare", "rare"), ("Epic", "epic"), ("Legendary", "legendary"), ("Mythical (1→50)", "mythical"))):
        b, m = rb(f"leg{num}E", tk)
        b, m = scale(b, m, 1.5)
        rows.append((tl, f"leg{num}{'ABCDE'[j]}", b, m))
    out.append(block(nm, rows))

# ---- Dynamic Stompers
out.append("## Dynamic Stompers (`leg67`)" + NL +
           "**Rare → Mythical, 3 types**, four looks B-E = Rare, Epic, Legendary, Mythical (Divine dropped). Reloaded stats for the native energy type, **boosted x1.25** (user). The red (heat, Blazing Stompers) and yellow (physical, Boulder Stompers) types are new recolours with the usual conversion *(derived)*: heat = explosive damage with the heat drain at x0.75 of the energy drain, physical = damage x1.25 with no drain. Names of the recolours are placeholders." + NL)
for nm, suf, mode in (("Dynamic Stompers (energy)", "", None), ("Blazing Stompers (heat)", "_heat", "h"), ("Boulder Stompers (physical)", "_phys", "p")):
    rows = []
    for j, (tl, tk) in enumerate((("Rare", "rare"), ("Epic", "epic"), ("Legendary", "legendary"), ("Mythical (1→50)", "mythical"))):
        b, m = rb("leg67E", tk)
        b, m = scale(b, m, 1.25)
        if mode == "h":
            b, m = to_heat(b, m)
        if mode == "p":
            b, m = to_phys(b, m)
        rows.append((tl, f"leg67{'BCDE'[j]}{suf}", b, m))
    out.append(block(nm, rows))

# ---- Supporters
out.append("## Lightning / Magma / Stalactite Supporters (`leg73`)" + NL +
           "**Epic → Ultimate, 3 types** (the Reloaded range, no band was given). C = Epic, D = Legendary, E = Mythical + Ultimate. Native blue is Lightning Supporters (energy); the red **Magma Supporters** (heat) and yellow **Stalactite Supporters** (physical) are new recolours with the usual conversion *(derived)*: heat = explosive damage with the heat drain at x0.75 of the energy drain, physical = damage x1.25 with no drain. Ultimate level 1 = Reloaded Divine, level 100 = HP and stomp damage x1.62 and drains x1.45 *(derived)*. Reloaded stats otherwise, not boosted." + NL)
for nm, suf, mode in (("Lightning Supporters (energy)", "", None), ("Magma Supporters (heat)", "_heat", "h"), ("Stalactite Supporters (physical)", "_phys", "p")):
    rows = []
    for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb("leg73E", tk)
        rows.append((tl, f"leg73{sp_}{suf}", b, m))
    b, m = ult_row(tiers("leg73E")["divine"]["base"])
    rows.append(("Ultimate (1→100)", f"leg73E{suf}", b, m))
    conv = []
    for tl, sp_, b, m in rows:
        if mode == "h":
            b, m = to_heat(b, m)
        if mode == "p":
            b, m = to_phys(b, m)
        conv.append((tl, sp_, b, m))
    out.append(block(nm, conv))

# ---- Striders (leg74)
out.append("## Scrap / Flare / Static Striders (`leg74`)" + NL +
           "**Common → Legendary, 3 types**, four looks A-D = Common, Rare, Epic, Legendary. Unnamed and unreleased in the data (placeholder names). The native yellow-orange is physical; red (heat) and blue (energy) are new recolours. *Invented* stats: each type takes the matching normal Reloaded ladder (Iron Boots / Scorching Feet / Charged Walkers, Common to Legendary, **not boosted**), and, as the jump leg it is (item-format note), **jump 3** instead of 2." + NL)
for nm, suf, src in (("Scrap Striders (physical)", "", "leg61E"), ("Flare Striders (heat)", "_heat", "leg60E"), ("Static Striders (energy)", "_elec", "leg62E")):
    rows = []
    for j, (tl, tk) in enumerate((("Common", "common"), ("Rare", "rare"), ("Epic", "epic"), ("Legendary", "legendary"))):
        b, m = rb(src, tk)
        b["jump"] = m["jump"] = 3
        rows.append((tl, f"leg74{'ABCD'[j]}{suf}", b, m))
    out.append(block(nm, rows))

# ---- Grave Diggers
out.append("## Grave / Pyre / Wraith Diggers (`leg76`)" + NL +
           "**Rare → Ultimate, 3 types** (the Reloaded range; no band was given). Four looks B-E = Rare, Epic, Legendary, Mythical + Ultimate. Native orange is the Reloaded **Grave Diggers** (physical, push 2); red (heat, Pyre Diggers) and blue (energy, Wraith Diggers) are new recolours. Conversion from a physical base *(derived)*: damage / 1.25, drain = 0.23 x average damage for heat and 0.31 x for energy (the Massive Feet ratios). Ultimate level 1 = Reloaded Divine, level 100 = HP and stomp damage x1.62 and drains x1.45. Reloaded stats otherwise, not boosted." + NL)


def from_phys(b, m, mode):
    b, m = dict(b), dict(m)
    for x in (b, m):
        a = x.pop("phyDmg")
        lo, hi = round(a[0] / 1.25), round(a[1] / 1.25)
        avg = (lo + hi) / 2
        if mode == "h":
            x["expDmg"] = [lo, hi]
            x["heaDmg"] = round(avg * .23)
        else:
            x["eleDmg"] = [lo, hi]
            x["eneDmg"] = round(avg * .31)
    return b, m


for nm, suf, mode in (("Grave Diggers (physical)", "", None), ("Pyre Diggers (heat)", "_heat", "h"), ("Wraith Diggers (energy)", "_elec", "e")):
    rows = []
    for tl, tk, sp_ in (("Rare", "rare", "B"), ("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb("leg76E", tk)
        rows.append((tl, f"leg76{sp_}{suf}", b, m))
    b, m = ult_row(tiers("leg76E")["divine"]["base"])
    rows.append(("Ultimate (1→100)", f"leg76E{suf}", b, m))
    out.append(block(nm, [(tl, sp_, *(from_phys(b, m, mode) if mode else (b, m))) for tl, sp_, b, m in rows]))

# ---- The Claw
out.append("## The Claw, The Pincer, The Fang (`leg77`)" + NL +
           "**Legendary → Ultimate, 3 types** (the Reloaded range; no band was given). D = Legendary, E = Mythical + Ultimate. A heavy, slow crawler: 450 HP, weight 150, no walk or jump listed. Native yellow is the Reloaded **The Claw** (physical); **The Pincer** (heat, red) and **The Fang** (energy, blue) are new recolours with names as placeholders. Conversion from the physical base *(derived)*: damage / 1.25, drain = 0.23 x average damage for heat and 0.31 x for energy. Ultimate level 1 = Reloaded Divine, level 100 = HP and stomp damage x1.62 and drains x1.45. Not boosted." + NL)
for nm, suf, mode in (("The Claw (physical)", "", None), ("The Pincer (heat)", "_heat", "h"), ("The Fang (energy)", "_elec", "e")):
    rows = []
    for tl, tk, sp_ in (("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
        b, m = rb("leg77E", tk)
        rows.append((tl, f"leg77{sp_}{suf}", b, m))
    b, m = ult_row(tiers("leg77E")["divine"]["base"])
    rows.append(("Ultimate (1→100)", f"leg77E{suf}", b, m))
    out.append(block(nm, [(tl, sp_, *(from_phys(b, m, mode) if mode else (b, m))) for tl, sp_, b, m in rows]))

# ---- Dynamite Boots
out.append("## Dynamite Boots and Recoil Stompers (`leg78`, `leg79`)" + NL +
           "**Epic → Mythical**, two items: Dynamite Boots (explosive) and its energy sibling Recoil Stompers (`leg79`), no physical version. C = Epic, D = Legendary, E = Mythical; the Reloaded Divine is dropped, no Ultimate. Reloaded stats, **buffed x1.5** (user): HP, stomp damage and heat drain. Weight, push, walk, jump, range stay." + NL)
rows = []
for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
    b, m = rb("leg78E", tk)
    b, m = scale(b, m, 1.5)
    rows.append((tl, f"leg78{sp_}", b, m))
out.append(block("Dynamite Boots (heat)", rows))
rows = []
for tl, tk, sp_ in (("Epic", "epic", "C"), ("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
    b, m = rb("leg79E", tk)
    b, m = scale(b, m, 1.5)
    rows.append((tl, f"leg79{sp_}", b, m))
out.append(block("Recoil Stompers (energy)", rows, "The energy sibling of Dynamite Boots (`leg79`), covered by the same decision: Epic → Mythical, x1.5, no Ultimate."))

# ---- Dropped
out.append("## Rolling Beasts (`wheels69`)" + NL +
           "**Legendary → Ultimate, physical only** (user: only the Reloaded tiers, no other types). D = Legendary, E = Mythical + Ultimate. Reloaded stats as they are; Ultimate level 1 = Reloaded Divine, level 100 = HP and stomp damage x1.62 *(derived)*. Not boosted." + NL)
rows = []
for tl, tk, sp_ in (("Legendary", "legendary", "D"), ("Mythical (1→50)", "mythical", "E")):
    b, m = rb("wheels69E", tk)
    rows.append((tl, f"wheels69{sp_}", b, m))
b, m = ult_row(tiers("wheels69E")["divine"]["base"])
rows.append(("Ultimate (1→100)", "wheels69E", b, m))
out.append(block("Rolling Beasts (physical)", rows))

out.append("## Dropped legs" + NL + "Dropped (user, 2026-09-29): **Fire / Steel / Thunder Stampede** (`leg27`), **Steel Walkers** (`leg2`) and **Fort Wall** (`leg7`). Sprites are in `Plans/Legs/_archive/dropped/`. **GOD MODE legs** (`leg1000`) are left for the boss slot (GOD MODE is the boss). ARMOR TANK's leg (`leg1001`) is enemy-only (see above)." + NL)

open("Plans/Legs/Leg Decisions.md", "w", encoding="utf-8").write(NL.join(out))
print("written", len(out))
