"""Regenerate Plans/Torsos/Torso Decisions.md (tables with a sprite per tier row).
Run from the project root: python tools/torso_notes.py
Stats come from data/items_selected.json (Reloaded packs) plus the rules written in each section's text."""
import json, statistics as S

d = json.load(open("data/items_selected.json", encoding="utf-8"))
d = d if isinstance(d, list) else d["items"]
by = {i["id"]: i for i in d}
_raw = json.load(open("data/items_raw.json", encoding="utf-8"))
for _i in (_raw if isinstance(_raw, list) else _raw["items"]):
    by.setdefault(_i["id"], _i)  # Grim Reaper (torso70E) is not in the roster, only in the raw list
T = lambda id: by[id]["stats"]["reloaded"]["tiers"]
K = ["weight", "health", "eneCap", "eneReg", "heaCap", "heaCol", "phyRes", "expRes", "eleRes"]

# medians of the 7 Epic -> Divine Reloaded torsos (used for invented families)
ED = [i["stats"]["reloaded"]["tiers"] for i in d if i["slot"] == "torsos" and (i.get("stats") or {}).get("reloaded")
      and i["stats"]["reloaded"]["transform_range"] == "E-D" and "divine" in i["stats"]["reloaded"]["tiers"]]


def median_block(tier):
    out = {}
    for k in K:
        b = [x[tier]["base"][k] for x in ED if k in x[tier]["base"]]
        m = [(x[tier].get("max") or x[tier]["base"])[k] for x in ED if k in (x[tier].get("max") or x[tier]["base"])]
        out[k] = (round(S.median(b)), round(S.median(m)))
    return out


MED = {t: median_block(t) for t in ("epic", "legendary", "mythical", "divine")}


def blk(mb):  # median block -> (base, max)
    return {k: v[0] for k, v in mb.items()}, {k: v[1] for k, v in mb.items()}


def rb(id, tier):  # reloaded block -> (base, max)
    v = T(id)[tier]
    b = dict(v["base"])
    return b, dict(v.get("max") or v["base"])


def scale(b, m, mult, keys=("health", "eneCap", "heaCap", "eneReg", "heaCol")):
    b, m = dict(b), dict(m)
    for x in (b, m):
        for k in keys:
            if k in x:
                x[k] = round(x[k] * mult)
    return b, m


def flav(b, m, el):
    b, m = dict(b), dict(m)
    for x in (b, m):
        if el == "e":
            x["eneCap"] = round(x["eneCap"] * 1.25)
            x["heaCap"] = round(x["heaCap"] * .8)
        if el == "h":
            x["eneCap"] = round(x["eneCap"] * .8)
            x["heaCap"] = round(x["heaCap"] * 1.25)
    return b, m


def ult(divine_b):  # Ultimate row from a Divine block: level 1 = divine, level 100 = x1.63 on HP and capacities
    b = dict(divine_b)
    m = dict(b)
    for k in ("health", "eneCap", "heaCap"):
        m[k] = round(b[k] * 1.63)
    return b, m


def cell(b, m, k):
    a, z = round(b.get(k, 0)), round(m.get(k, b.get(k, 0)))
    return f"{a}→{z}" if a != z else f"{a}"


def img(sprite, w=64):
    return f"![[Torsos/sprites/{sprite}.png\\|{w}]]"


def table(rows):
    """rows: (tier label, sprite id, base, max, res text or None). One table, sprite per row."""
    o = ["| Tier | Look | HP | Energy cap | Heat cap | Regen | Cooling | Res (phy/exp/ele) |", "|---|---|---|---|---|---|---|---|"]
    for lab, sp, b, m, res in rows:
        r = res or f"{b.get('phyRes',0)}/{b.get('expRes',0)}/{b.get('eleRes',0)}"
        if r == "0/0/0":
            r = "–"
        o.append(f"| {lab} | {img(sp)} | {cell(b,m,'health')} | {cell(b,m,'eneCap')} | {cell(b,m,'heaCap')} | {b['eneReg']} | {b['heaCol']} | {r} |")
    return "\n".join(o)


def block(title, weight, rows, note=""):
    return f"#### {title}\nWeight {weight}." + (f" {note}" if note else "") + "\n\n" + table(rows) + "\n"


out = ["""# Torso Decisions

Sheet to plan from: [[Unplanned Torsos]]. Generated by `tools/torso_notes.py` (edit the script, not this file). Every table is **base → max level** inside the tier; regen, cooling, resistances and weight do not grow inside a tier. *Derived / invented* numbers are called out per family; everything else is straight from the Reloaded data.

| Family | Tiers | Types |
|---|---|---|
| Brutality (was God Mode) | Mythical → Ultimate | 3 |
| Nightmare / Interceptor / Sith | Common → Mythical (×1.35) | 3 |
| Ember, Boiler | Epic → Legendary | 1 each |
| Bastion | Rare → Epic | 3 |
| Sentinel | Epic → Ultimate | 3 |
| Battery Armors | Epic → Mythical | 3 |
| Spectral / Heat / Energy Armors | Legendary → Ultimate | 3 |
| Cyber Armors | Mythical only | 3 |
| Free Armors | Legendary → Ultimate | 3 |
| Platinum Vests | Legendary → Ultimate | 3 |
| Guardians | Rare → Epic | 3 |
| Galaxus | Mythical → Ultimate | 3 |
| MetroLens set (Grim Reaper looks) | Epic → Legendary | 3 |
| HellFire set (Grim Reaper looks) | Legendary → Ultimate | 3 |
| Avenger, Windigo, Zarkares | Epic → Ultimate | 3 each |
| Diamond Shell | Mythical only | 3 |
| Naga | Rare → Legendary | 3 |
| Archimonde | Legendary → Mythical | 3 |
| Sabertooth | Mythical only | 2 (heat, energy) |
| Jeep, Tank, ARMOR TANK | enemy-only, no drops | – |
"""]

# ---- God Mode
gb = {"weight": 341, "health": 1070, "eneCap": 225, "eneReg": 64, "heaCap": 298, "heaCol": 88, "phyRes": 22, "expRes": 16, "eleRes": 22}
gm = dict(gb, health=1514, eneCap=319, heaCap=391)
gu1 = dict(gm, health=2200, eneCap=463, heaCap=567)
gu2 = dict(gu1, health=3590, eneCap=755, heaCap=924)
out.append("## Brutality (`torso52`)\n**Mythical → Ultimate, 3 types.** The player-facing name is **Brutality** (decided 2026-09-29); **GOD MODE is the name of the actual boss** (boss parts `torsoBoss5` / `legBoss5`, boss slot not planned yet). The art is the **lighter Reloaded twin `torso52`** (easier to recolour); the dark Legacy `torso1000` is dropped from the roster. Native red is heat; blue (energy) and yellow (physical) are new recolours *(user asked for the lighter art to colour it; confirm the extra types)*. Mythical level 1 starts at the Reloaded **Divine** stats of `torso52` (heat-heavy, as is), not the Legacy numbers. Level 50 is level 1 × the Reloaded Mythical growth (HP ×1.415, energy cap ×1.418, heat cap ×1.31). Ultimate level 1 continues from Mythical level 50 × 1.45, then ×1.63 to level 100. Energy is the mirror (caps and regen / cooling swapped), physical the average. *Levels 50 and up are derived.* A maxed Brutality mech (legs ~800, two Platinum Plating ~1,080) is ~5,500 HP. **Open:** how Brutality is obtained.\n")

def gconv(b, m, mode):
    b, m = dict(b), dict(m)
    for x in (b, m):
        e, h = x["eneCap"], x["heaCap"]
        if mode == "e": x["eneCap"], x["heaCap"] = h, e
        if mode == "p": x["eneCap"] = x["heaCap"] = round((e + h) / 2)
    if mode == "e": b["eneReg"], b["heaCol"] = b["heaCol"], b["eneReg"]
    if mode == "p": b["eneReg"] = b["heaCol"] = round((b["eneReg"] + b["heaCol"]) / 2)
    return b, m
for nm, suf, mode in (("Brutality (heat)", "", None), ("Violence (energy)", "_elec", "e"), ("Genocide (physical)", "_phys", "p")):
    rows = []
    for tl, b, m in (("Mythical (1→50)", gb, gm), ("Ultimate (1→100)", gu1, gu2)):
        rows.append((tl, "torso52" + suf, *gconv(b, m, mode), None))
    out.append(block(nm, 341, rows))

# ---- Nightmare / Interceptor / Sith
out.append("## Nightmare / Interceptor / Sith (`torso60–62`)\n**Common → Mythical, no Ultimate** (Reloaded Divine dropped). Five looks A–E = Common, Rare, Epic, Legendary, Mythical. **HP, energy and heat capacity, regen and cooling ×1.35** (user, to make up for no Ultimate); weight and resistances unchanged. Boosted Mythical max is ~1,160–1,480 HP.\n")
for n, nm, el in (("60", "Sith", "electric"), ("61", "Nightmare", "explosive"), ("62", "Interceptor", "physical")):
    rows = []
    for j, (tl, tk) in enumerate((("Common", "common"), ("Rare", "rare"), ("Epic", "epic"), ("Legendary", "legendary"), ("Mythical", "mythical"))):
        b, m = rb(f"torso{n}E", tk)
        b, m = scale(b, m, 1.35)
        rows.append((tl, f"torso{n}{'ABCDE'[j]}", b, m, None))
    out.append(block(f"{nm} ({el})", T(f"torso{n}E")["common"]["base"]["weight"], rows))

# ---- Ember, Boiler
E_, L_ = blk(MED["epic"]), blk(MED["legendary"])
out.append("## Ember (`torso7`, `torso7B`) and Boiler (`torso75C/D`)\n**Epic → Legendary.** *Invented* from the median of the 7 Epic → Divine Reloaded torsos. Ember: the Legacy Two Head look is Epic and the Legacy Ember look Legendary, one family named Ember, weight 263. Boiler is unnamed and unreleased in the data (placeholder name), weight 346.\n")
out.append(block("Ember", 263, [("Epic", "torso7", *E_, None), ("Legendary", "torso7B", *L_, None)]))
out.append(block("Boiler", 346, [("Epic", "torso75C", *E_, None), ("Legendary", "torso75D", *L_, None)]))

# ---- Bastion
rare = ({"weight": 312, "health": 171, "eneCap": 40, "eneReg": 16, "heaCap": 55, "heaCol": 20, "phyRes": 3, "expRes": 3, "eleRes": 3},
        {"weight": 312, "health": 284, "eneCap": 70, "eneReg": 16, "heaCap": 97, "heaCol": 20, "phyRes": 3, "expRes": 3, "eleRes": 3})
epic85 = ({"weight": 312, "health": 293, "eneCap": 64, "eneReg": 28, "heaCap": 88, "heaCol": 35, "phyRes": 7, "expRes": 7, "eleRes": 7},
          {"weight": 312, "health": 418, "eneCap": 92, "eneReg": 28, "heaCap": 126, "heaCol": 35, "phyRes": 7, "expRes": 7, "eleRes": 7})
out.append("## Bastion (`torso85B/C`)\n**Rare → Epic, 3 types.** B = Rare, C = Epic. Native orange is physical; red and blue are new recolours. *Invented* stats: the median of the Nightmare / Interceptor / Sith Rare and Epic blocks. Element flavour: energy version energy cap ×1.25 and heat cap ×0.8, heat version the opposite. Weight 312.\n")
for nm, suf, el in (("Bastion (physical)", "", "p"), ("Cinder Bastion (heat)", "_heat", "h"), ("Arc Bastion (energy)", "_elec", "e")):
    out.append(block(nm, 312, [("Rare", f"torso85B{suf}", *flav(*rare, el), None), ("Epic", f"torso85C{suf}", *flav(*epic85, el), None)]))

# ---- Sentinel
out.append("## Sentinel (`torso92C/D/E`)\n**Epic → Ultimate, 3 types.** C = Epic, D = Legendary, E = Mythical + Ultimate. Native blue is energy; red and yellow are new recolours. *Invented* stats from the Reloaded medians (same flavour rule as Bastion); Ultimate level 1 = Reloaded Divine, level 100 = ×1.63 on HP and capacities. Weight 346.\n")
for nm, suf, el in (("Arc Sentinel (energy)", "", "e"), ("Flame Sentinel (heat)", "_heat", "h"), ("Iron Sentinel (physical)", "_phys", "p")):
    rows = []
    for tl, sp, mb in (("Epic", "C", MED["epic"]), ("Legendary", "D", MED["legendary"]), ("Mythical (1→50)", "E", MED["mythical"])):
        rows.append((tl, f"torso92{sp}{suf}", *flav(*blk(mb), el), None))
    rows.append(("Ultimate (1→100)", f"torso92E{suf}", *flav(*ult(blk(MED["divine"])[0]), el), None))
    out.append(block(nm, 346, rows))


# ---- Battery armors
out.append("## Battery Armors (`torso93–95`)\n**Epic → Mythical, no Ultimate.** C = Epic, D = Legendary, E = Mythical. Reloaded stats as they are. `torso95` has no data, so **Heat Battery Armor** is an *invented* mirror of the energy one (energy and heat capacity swapped) with a placeholder name. `torso93E`'s Mythical base HP is `8003` in the data (typo, taken as 803).\n")


def battery(id, fix=None, swap=False):
    rows = []
    for tl, sp, tk in (("Epic", "C", "epic"), ("Legendary", "D", "legendary"), ("Mythical (1→50)", "E", "mythical")):
        b, m = rb(id, tk)
        if fix and tk in fix:
            b.update(fix[tk])
        if swap:
            for x in (b, m):
                x["eneCap"], x["heaCap"] = x["heaCap"], x["eneCap"]
        rows.append((tl, sp, b, m))
    return rows


for nm, num, wt, kw in (("Energy Battery Armor (energy)", "93", 346, dict(id="torso93E", fix={"mythical": {"health": 803}})),
                        ("Battery Armor (physical)", "94", 360, dict(id="torso94E")),
                        ("Heat Battery Armor (heat, invented)", "95", 346, dict(id="torso93E", fix={"mythical": {"health": 803}}, swap=True))):
    out.append(block(nm, wt, [(tl, f"torso{num}{sp}", b, m, None) for tl, sp, b, m in battery(**kw)]))


# ---- Legendary -> Ultimate sets
def leg_ult(id):
    r = []
    for tl, tk in (("Legendary", "legendary"), ("Mythical (1→50)", "mythical")):
        b, m = rb(id, tk)
        r.append((tl, b, m))
    b, m = ult(T(id)["divine"]["base"])
    r.append(("Ultimate (1→100)", b, m))
    return r


out.append("## Spectral / Heat / Energy Armors (`torso89–91`)\n**Legendary → Ultimate, 3 types.** D = Legendary, E = Mythical + Ultimate. **No resistances, very high HP** (user): the Reloaded data already has none and the highest torso HP, so it is used as is. Ultimate level 1 = Reloaded Divine, level 100 = ×1.63 on HP and capacities *(derived)*. Weight 370.\n")
for nm, num, sp in (("Rusty Energy Armor (energy)", "89", ("torso89D", "torso89E", "torso89E")), ("Hollow Spectral Armor (physical)", "90", ("torso90D", "torso90E", "torso90E")), ("Fractured Heat Armor (heat)", "91", ("torso91D", "torso91E", "torso91E"))):
    out.append(block(nm, 370, [(tl, sp[j], b, m, None) for j, (tl, b, m) in enumerate(leg_ult(f"torso{num}E"))]))

# ---- Cyber armors
out.append("## Cyber Armors (`torso97–99`)\n**Mythical only.** **Much higher resistances at the cost of HP** (user): 60 to the armor's own element and 40 to the others (the data has none), HP ×0.7 of Reloaded Mythical *(both invented)*. Capacities and regen as Reloaded. Weight 370.\n")
for nm, num, res in (("Hollow Cyber Armor (physical)", "97", "60/40/40"), ("Fractured Cyber Armor (heat)", "98", "40/60/40"), ("Rusty Cyber Armor (energy)", "99", "40/40/60")):
    b, m = rb(f"torso{num}E", "mythical")
    b, m = scale(b, m, .7, keys=("health",))
    out.append(block(nm, 370, [("Mythical (1→50)", f"torso{num}E", b, m, res)]))

# ---- Free armors
out.append("## Free Armors (`torso96D/E`)\n**Legendary → Ultimate, 3 types** (the Reloaded range; no band was given). D = Legendary, E = Mythical + Ultimate. The gimmick is a **near-zero energy capacity** with a big heat pool. Orange (physical) is Reloaded's Energy Free Armor. Red (heat) keeps the energy-free gimmick with heat cap ×1.25. Blue (energy) is the mirror, heat-free (capacities and regen/cooling swapped, energy cap ×1.25). Red and blue are new recolours; their names and stats are *invented*. Weight 335.\n")


def free(mode):
    r = []
    for j, (tl, b, m) in enumerate(leg_ult("torso96E")):
        b, m = dict(b), dict(m)
        for x in (b, m):
            if mode == "h":
                x["heaCap"] = round(x["heaCap"] * 1.25)
            if mode == "m":
                x["eneCap"], x["heaCap"] = round(x["heaCap"] * 1.25), x["eneCap"]
        if mode == "m":
            b["eneReg"], b["heaCol"] = b["heaCol"], b["eneReg"]
        r.append((tl, b, m))
    return r


for nm, suf, mode in (("Energy Free Armor (physical)", "", None), ("Furnace Armor (heat)", "_heat", "h"), ("Heat Free Armor (energy)", "_elec", "m")):
    sp = (f"torso96D{suf}", f"torso96E{suf}", f"torso96E{suf}")
    out.append(block(nm, 335, [(tl, sp[j], b, m, None) for j, (tl, b, m) in enumerate(free(mode))]))

# ---- Vests
out.append("## Platinum Vests (`torso86–87`)\n**Legendary → Ultimate, 3 types.** D = Legendary, E = Mythical + Ultimate. Reloaded names and stats as they are, with the big physical resistance (27 → 55); the physical vest has a big electric resistance instead. Ultimate level 1 = Reloaded Divine, level 100 = ×1.63 on HP and capacities *(derived)*. Weight 346.\n")
for nm, id_, sp in (("Molten Platinum Vest (heat)", "torso86E", ("torso86D", "torso86E", "torso86E")), ("Lightning Platinum Vest (energy)", "torso87E", ("torso87D", "torso87E", "torso87E")), ("Hardened Platinum Vest (physical)", "torso87E2", ("torso87D2", "torso87E2", "torso87E2"))):
    out.append(block(nm, 346, [(tl, sp[j], b, m, None) for j, (tl, b, m) in enumerate(leg_ult(id_))]))


# ---- Guardians
out.append("## Guardians (`torso15`, `torso15B`, `torso16`, `torso16B`)\n**Rare → Epic, 3 types.** The A look (Ruby / Emerald) is Rare, the B look (Fire / Electric Guardian) is Epic. Red is heat, green is energy (their Legacy colours, kept), and yellow (physical) is a new recolour of the red one. *Invented* stats: the Bastion Rare / Epic block (median of the Nightmare / Interceptor / Sith), element flavour as Bastion. Weight 366 (the Legacy Fire Guardian).\n")
for nm, sp, el in (("Fire Guardian (heat)", ("torso15", "torso15B"), "h"), ("Electric Guardian (energy)", ("torso16", "torso16B"), "e"), ("Gold Guardian (physical)", ("torso15_phys", "torso15B_phys"), "p")):
    out.append(block(nm, 366, [("Rare", sp[0], *flav(*rare, el), None), ("Epic", sp[1], *flav(*epic85, el), None)]))

# ---- Galaxus
out.append("## Galaxus Model A / B / C (`torso42`)\n**Mythical → Ultimate, 3 types.** Model A physical (`torso42B`), Model B heat (`torso42A`), Model C energy (`torso42C`); one look each. *Invented* stats: the median Reloaded Mythical and Divine blocks, element flavour as Bastion, plus **+8 resistance to the model's own element** (the Legacy ones had a small own-element resistance). Ultimate level 1 = median Divine, level 100 = x1.63 on HP and capacities. Weight 409.\n")
def galaxus(el, own):
    rows = []
    for tl, mb in (("Mythical (1→50)", MED["mythical"]),):
        b, m = flav(*blk(mb), el)
        rows.append((tl, b, m))
    b, m = ult(blk(MED["divine"])[0]); b, m = flav(b, m, el)
    rows.append(("Ultimate (1→100)", b, m))
    out_rows = []
    for tl, b, m in rows:
        b, m = dict(b), dict(m)
        for x in (b, m): x[own] = x[own] + 8
        out_rows.append((tl, b, m))
    return out_rows
for nm, sp, el, own in (("Galaxus Model A (physical)", "torso42B", "p", "phyRes"), ("Galaxus Model B (heat)", "torso42A", "h", "expRes"), ("Galaxus Model C (energy)", "torso42C", "e", "eleRes")):
    out.append(block(nm, 409, [(tl, sp, b, m, None) for tl, b, m in galaxus(el, own)]))

# ---- Grim Reaper looks
out.append("## Grim Reaper looks on MetroLens and Hellfire (`torso70`, `torso46`, `torso47`)\n**Two sets, each in 3 types** (blue = energy, native; red = heat and yellow = physical are new recolours). Stats are the **Reloaded Grim Reaper ladder** (`torso70`, electric) for the matching tier. **Set 1, MetroLens: Epic and Legendary.** Epic = Grim Reaper's Epic look (`torso70C`), Legendary = MetroLens (`torso47`). **Set 2, HellFire: Legendary, Mythical and Ultimate.** Legendary = Grim Reaper's Mythical look (`torso70E`), Mythical and Ultimate = Hellfire (`torso46`). **Boosted x1.35** (HP, capacities, regen and cooling; user: the plain Grim Reaper ladder is tame next to the other torsos, Grim Reaper is a Rare-to-Divine item whose Mythical is only 621 HP). **The HellFire set goes to Ultimate** (Ultimate level 1 = Reloaded Divine x1.35, level 100 = x1.63 on HP and capacities *(derived)*); the MetroLens set still ends at Legendary. Heat is the mirror of the energy stats (energy and heat capacity, regen and cooling swapped), physical is the average of the two *(derived)*. Weight 329. Names: MetroLens / CinderLens / IronLens and Stormfire / HellFire / Solarfire (placeholders except MetroLens and HellFire).\n")
GRIM_BOOST = 1.35  # user: the Grim Reaper ladder felt too tame next to the other torsos


def grim(mode, tiers):
    r = []
    for tl, tk in tiers:
        if tk == "divine":
            b, m = ult(T("torso70E")["divine"]["base"])
        else:
            b, m = rb("torso70E", tk)
        b, m = scale(b, m, GRIM_BOOST)
        for x in (b, m):
            e, h = x["eneCap"], x["heaCap"]
            if mode == "h": x["eneCap"], x["heaCap"] = h, e
            if mode == "p": x["eneCap"] = x["heaCap"] = round((e + h) / 2)
        if mode == "h": b["eneReg"], b["heaCol"] = b["heaCol"], b["eneReg"]
        if mode == "p": b["eneReg"] = b["heaCol"] = round((b["eneReg"] + b["heaCol"]) / 2)
        r.append((tl, b, m))
    return r


SET1 = (("Epic", "epic"), ("Legendary", "legendary"))
SET2 = (("Legendary", "legendary"), ("Mythical (1→50)", "mythical"), ("Ultimate (1→100)", "divine"))
for nm, sprites, mode, tiers in (
        ("MetroLens (energy)", ("torso70C", "torso47"), None, SET1), ("CinderLens (heat)", ("torso70C_heat", "torso47_heat"), "h", SET1), ("IronLens (physical)", ("torso70C_phys", "torso47_phys"), "p", SET1),
        ("Stormfire (energy)", ("torso70E", "torso46", "torso46"), None, SET2), ("Hellfire (heat)", ("torso70E_heat", "torso46_heat", "torso46_heat"), "h", SET2), ("Solarfire (physical)", ("torso70E_phys", "torso46_phys", "torso46_phys"), "p", SET2)):
    out.append(block(nm, 329, [(tl, sprites[j], b, m, None) for j, (tl, b, m) in enumerate(grim(mode, tiers))]))

# ---- Avenger / Windigo / Zarkares
out.append("## Avenger, Windigo, Zarkares (`torso82`, `torso83`, `torso84`)\n**Epic → Ultimate, 3 types each.** C = Epic, D = Legendary, E = Mythical + Ultimate (the Reloaded range; no band was given). Reloaded stats for the native type, as they are; the other two are new recolours with the stats *derived*: Avenger (orange, physical) is balanced, so heat / energy use the usual flavour (the favoured cap x1.25, the other x0.8); Windigo and Zarkares carry heat-heavy Reloaded stats (Windigo's orange art is recoloured red for the heat version, the orange stays as its physical version), so energy is the mirror (caps and regen / cooling swapped) and physical the average of the two. Ultimate level 1 = Reloaded Divine, level 100 = x1.63 on HP and capacities. Names of the non-Reloaded types are placeholders.\n")
def three(id, native, mode):
    """native: 'p' (balanced) or 'h' (heat-heavy). mode: 'p'|'h'|'e' type wanted."""
    r = []
    for tl, tk in (("Epic", "epic"), ("Legendary", "legendary"), ("Mythical (1→50)", "mythical"), ("Ultimate (1→100)", "divine")):
        b, m = ult(T(id)["divine"]["base"]) if tk == "divine" else rb(id, tk)
        b, m = dict(b), dict(m)
        if native == "p" and mode in ("h", "e"):
            b, m = flav(b, m, mode)
        if native == "h" and mode in ("e", "p"):
            for x in (b, m):
                e, h = x["eneCap"], x["heaCap"]
                if mode == "e": x["eneCap"], x["heaCap"] = h, e
                else: x["eneCap"] = x["heaCap"] = round((e + h) / 2)
            if mode == "e": b["eneReg"], b["heaCol"] = b["heaCol"], b["eneReg"]
            else: b["eneReg"] = b["heaCol"] = round((b["eneReg"] + b["heaCol"]) / 2)
        r.append((tl, b, m))
    return r
for nm, num, wt, native, mode, suf in (
        ("Avenger (physical)", "82", 350, "p", "p", ""), ("Betrayer (heat)", "82", 350, "p", "h", "_heat"), ("Pacifist (energy)", "82", 350, "p", "e", "_elec"),
        ("Hauler (physical)", "83", 345, "h", "p", ""), ("Windigo (heat)", "83", 345, "h", "h", "_heat"), ("Shipper (energy)", "83", 345, "h", "e", "_elec"),
        ("Blast Furnace (physical)", "84", 362, "h", "p", "_phys"), ("Zarkares (heat)", "84", 362, "h", "h", ""), ("Arc Furnace (energy)", "84", 362, "h", "e", "_elec")):
    sprites = (f"torso{num}C{suf}", f"torso{num}D{suf}", f"torso{num}E{suf}", f"torso{num}E{suf}")
    out.append(block(nm, wt, [(tl, sprites[j], b, m, None) for j, (tl, b, m) in enumerate(three(f"torso{num}E", native, mode))]))

# ---- Diamond Shell / Naga / Archimonde / Sabertooth
out.append("## Diamond Shell, Naga, Archimonde, Sabertooth (`torso56A`, `torso78`, `torso67`, `torso88`)\nNew recolours for the missing types (all recolours are hue shifts of the accent). Type conversion: from a balanced block, heat / energy use the usual flavour rule (the favoured cap x1.25, the other x0.8); from an energy- or heat-heavy block, the opposite type is the mirror (caps and regen / cooling swapped) and physical the average. Placeholder names except the Reloaded ones.\n- **Diamond Shell (`torso56A`): Mythical only, 3 types.** The Legacy shell (195 HP but 20/20/20 resistance and balanced caps) becomes a *balanced Mythical* torso: the median Mythical block with balanced caps (average of the median caps) and equal resistance 24/24/24 *(invented)*. Native red is heat.\n- **Naga (`torso78`): Rare → Legendary, 3 types.** C = Rare, D = Epic, E = Legendary. Epic and Legendary are the Reloaded Naga (electric, energy-heavy); Rare is Epic / 1.7 *(derived)* with the Rare resistances of the Nightmare / Sith trio. Native blue is energy.\n- **Archimonde (`torso67`): Legendary → Mythical, 3 types.** D = Legendary, E = Mythical. Reloaded stats (balanced, physical). Native orange is physical.\n- **Sabertooth (`torso88`): Mythical only, heat + energy only** (no physical). Reloaded Mythical stats (heat-heavy). Native red is heat.\n")
def conv(b, m, native, mode):
    b, m = dict(b), dict(m)
    if native == "b":  # balanced -> flavour
        if mode in ("h", "e"): b, m = flav(b, m, mode)
        return b, m
    for x in (b, m):  # heat- or energy-heavy -> mirror / average
        e, h = x["eneCap"], x["heaCap"]
        if mode == "swap": x["eneCap"], x["heaCap"] = h, e
        if mode == "p": x["eneCap"] = x["heaCap"] = round((e + h) / 2)
    if mode == "swap": b["eneReg"], b["heaCol"] = b["heaCol"], b["eneReg"]
    if mode == "p": b["eneReg"] = b["heaCol"] = round((b["eneReg"] + b["heaCol"]) / 2)
    return b, m
# Diamond Shell: balanced Mythical
_mb, _mm = blk(MED["mythical"])
for _x in (_mb, _mm):
    pass
_bal = lambda d_, e_, h_: dict(d_, eneCap=round((e_ + h_) / 2), heaCap=round((e_ + h_) / 2))
_db = _bal(_mb, _mb["eneCap"], _mb["heaCap"]); _dm = _bal(_mm, _mm["eneCap"], _mm["heaCap"])
for _x in (_db, _dm):
    _x["eneReg"] = _x["heaCol"] = round((_mb["eneReg"] + _mb["heaCol"]) / 2)
    _x["phyRes"] = _x["expRes"] = _x["eleRes"] = 24
for nm, suf, mode in (("Diamond Shell (heat)", "", "h"), ("Sapphire Shell (energy)", "_elec", "e"), ("Topaz Shell (physical)", "_phys", "p")):
    b, m = conv(_db, _dm, "b", mode)
    out.append(block(nm, 369, [("Mythical (1→50)", "torso56A" + suf, b, m, None)]))
# Naga: energy native, Rare derived
def naga_rows(mode):
    r = []
    b, m = rb("torso78E", "epic")
    rb_, rm_ = {k: (round(v / 1.7) if k in ("health", "eneCap", "heaCap", "eneReg", "heaCol") else v) for k, v in b.items()}, {k: (round(v / 1.7) if k in ("health", "eneCap", "heaCap") else v) for k, v in m.items()}
    rb_.update(phyRes=3, expRes=3, eleRes=2); rm_.update(phyRes=3, expRes=3, eleRes=2)
    rows = [("Rare", rb_, rm_)] + [(tl, *rb("torso78E", tk)) for tl, tk in (("Epic", "epic"), ("Legendary", "legendary"))]
    for tl, b, m in rows:
        b, m = conv(b, m, "x", mode) if mode else (b, m)
        r.append((tl, b, m))
    return r
for nm, suf, mode in (("Naga (energy)", "", None), ("Cerberus (heat)", "_heat", "swap"), ("Hydra (physical)", "_phys", "p")):
    out.append(block(nm, 335, [(tl, f"torso78{'CDE'[j]}{suf}", b, m, None) for j, (tl, b, m) in enumerate(naga_rows(mode))]))
# Archimonde: physical native, balanced
def arch(mode):
    r = []
    for tl, tk in (("Legendary", "legendary"), ("Mythical (1→50)", "mythical")):
        b, m = rb("torso67E", tk)
        b, m = conv(b, m, "b", mode)
        r.append((tl, b, m))
    return r
for nm, suf, mode in (("Archimonde (physical)", "", "p"), ("Rock Barrier (heat)", "_heat", "h"), ("Storm Barrier (energy)", "_elec", "e")):
    out.append(block(nm, 363, [(tl, f"torso67{'DE'[j]}{suf}", b, m, None) for j, (tl, b, m) in enumerate(arch(mode))]))
# Sabertooth: heat native
for nm, suf, mode in (("Sabertooth (heat)", "", None), ("Arctic Fox (energy)", "_elec", "swap")):
    b, m = rb("torso88", "mythical")
    if mode: b, m = conv(b, m, "x", mode)
    out.append(block(nm, 362, [("Mythical (1→50)", "torso88" + suf, b, m, None)]))

# ---- Enemy-only
out.append("## Enemy-only torsos: Jeep, Tank, ARMOR TANK (`torso1001–1003`)\n**Enemy use only, no drops** (decided 2026-09-29): kept in the torso slot (user confirmed, although the art looks like tank treads), for enemy and boss mechs; never a reward and never on the player ladder. They keep their **Legacy stats as they are** (no tiers, no levels); the enemy scaling is designed with the campaign.\n")
out.append("| Sprite | Name | Weight | HP | Energy cap / regen | Heat cap / cooling | Res (phy/exp/ele) |\n|---|---|---|---|---|---|---|")
for _id in ("torso1001", "torso1002", "torso1002_2", "torso1002_3", "torso1003", "torso1003_2", "torso1003_3"):
    _x = by[_id]["stats"]["legacy"][0]["stats"]
    _r = "–" if "phyRes" not in _x else f"{_x['phyRes']}/{_x['expRes']}/{_x['eleRes']}"
    out.append(f"| {img(_id)} | {by[_id]['stats']['legacy'][0]['name']} | {_x['weight']} | {_x['health']} | {_x['eneCap']} / {_x['eneReg']} | {_x['heaCap']} / {_x['heaCol']} | {_r} |")
out.append("")

open("Plans/Torsos/Torso Decisions.md", "w", encoding="utf-8").write("\n".join(out))
print("written", len(out))
